[2025-04-18T16:18:30.752+1000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T16:18:30.791+1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_world_task manual__2025-04-18T06:18:16.230570+00:00 [queued]>
[2025-04-18T16:18:30.817+1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_world_task manual__2025-04-18T06:18:16.230570+00:00 [queued]>
[2025-04-18T16:18:30.818+1000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-18T16:18:30.858+1000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): hello_world_task> on 2025-04-18 06:18:16.230570+00:00
[2025-04-18T16:18:30.872+1000] {standard_task_runner.py:72} INFO - Started process 81402 to run task
[2025-04-18T16:18:30.895+1000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'hello_world', 'hello_world_task', 'manual__2025-04-18T06:18:16.230570+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/var/folders/05/dgx_ky6d3n9f_vxn26lcln1h0000gn/T/tmpevhyp22w']
[2025-04-18T16:18:30.907+1000] {standard_task_runner.py:105} INFO - Job 12: Subtask hello_world_task
[2025-04-18T16:18:31.044+1000] {task_command.py:467} INFO - Running <TaskInstance: hello_world.hello_world_task manual__2025-04-18T06:18:16.230570+00:00 [running]> on host anurags-macbook-pro.local
[2025-04-18T16:18:31.351+1000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='anuragthakur' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_world_task' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T06:18:16.230570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T06:18:16.230570+00:00'
[2025-04-18T16:18:31.354+1000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T16:18:31.430+1000] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/05/dgx_ky6d3n9f_vxn26lcln1h0000gn/T
[2025-04-18T16:18:31.434+1000] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', 'echo Hello world once again using "with"!!']
[2025-04-18T16:18:31.452+1000] {subprocess.py:99} INFO - Output:
[2025-04-18T16:18:31.466+1000] {subprocess.py:106} INFO - Hello world once again using with!!
[2025-04-18T16:18:31.469+1000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-18T16:18:31.533+1000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T16:18:31.537+1000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_world_task, run_id=manual__2025-04-18T06:18:16.230570+00:00, execution_date=20250418T061816, start_date=20250418T061830, end_date=20250418T061831
[2025-04-18T16:18:31.596+1000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T16:18:31.638+1000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-18T16:18:31.641+1000] {local_task_job_runner.py:245} INFO - ::endgroup::
