[2025-04-18T16:46:17.517+1000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-18T16:46:17.547+1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskA manual__2025-04-18T06:46:09.446866+00:00 [queued]>
[2025-04-18T16:46:17.565+1000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: executing_multiple_tasks.taskA manual__2025-04-18T06:46:09.446866+00:00 [queued]>
[2025-04-18T16:46:17.565+1000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-18T16:46:17.601+1000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): taskA> on 2025-04-18 06:46:09.446866+00:00
[2025-04-18T16:46:17.615+1000] {standard_task_runner.py:72} INFO - Started process 85229 to run task
[2025-04-18T16:46:17.637+1000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'executing_multiple_tasks', 'taskA', 'manual__2025-04-18T06:46:09.446866+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/execute_multiple_tasks.py', '--cfg-path', '/var/folders/05/dgx_ky6d3n9f_vxn26lcln1h0000gn/T/tmpgfizv76j']
[2025-04-18T16:46:17.647+1000] {standard_task_runner.py:105} INFO - Job 16: Subtask taskA
[2025-04-18T16:46:17.762+1000] {task_command.py:467} INFO - Running <TaskInstance: executing_multiple_tasks.taskA manual__2025-04-18T06:46:09.446866+00:00 [running]> on host anurags-macbook-pro.local
[2025-04-18T16:46:17.998+1000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='anuragthakur' AIRFLOW_CTX_DAG_ID='executing_multiple_tasks' AIRFLOW_CTX_TASK_ID='taskA' AIRFLOW_CTX_EXECUTION_DATE='2025-04-18T06:46:09.446866+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-18T06:46:09.446866+00:00'
[2025-04-18T16:46:18.001+1000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-18T16:46:18.069+1000] {subprocess.py:78} INFO - Tmp dir root location: /var/folders/05/dgx_ky6d3n9f_vxn26lcln1h0000gn/T
[2025-04-18T16:46:18.072+1000] {subprocess.py:88} INFO - Running command: ['/bin/bash', '-c', '\n        echo TASK A has started!\n        \n        for i in {1...10}\n        do\n            echo TASK A printing $i\n        done\n        \n        echo TASK A ended!\n    ']
[2025-04-18T16:46:18.089+1000] {subprocess.py:99} INFO - Output:
[2025-04-18T16:46:18.106+1000] {subprocess.py:106} INFO - TASK A has started!
[2025-04-18T16:46:18.109+1000] {subprocess.py:106} INFO - TASK A printing {1...10}
[2025-04-18T16:46:18.111+1000] {subprocess.py:106} INFO - TASK A ended!
[2025-04-18T16:46:18.112+1000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-04-18T16:46:18.170+1000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-18T16:46:18.173+1000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=executing_multiple_tasks, task_id=taskA, run_id=manual__2025-04-18T06:46:09.446866+00:00, execution_date=20250418T064609, start_date=20250418T064617, end_date=20250418T064618
[2025-04-18T16:46:18.259+1000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-18T16:46:18.369+1000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-04-18T16:46:18.374+1000] {local_task_job_runner.py:245} INFO - ::endgroup::
